version: 2
references:
  test: &test
    steps:
      - checkout
      - restore_cache:
          key: 1-bundler-{{ checksum "xccoveralls.gemspec" }}
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundler
      - save_cache:
          key: 1-bundler-{{ checksum "xccoveralls.gemspec" }}
          paths:
            - vendor/bundler
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec \
              --format documentation \
              --format RspecJunitFormatter --out test_report.xml
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: result.xml

jobs:
  test-9.4.0:
    macos:
      xcode: '9.4.0'
    <<: *test

  test-9.3.1:
    macos:
      xcode: '9.3.1'
    <<: *test

  test-9.3.0:
    macos:
      xcode: '9.3.0'
    <<: *test

workflows:
  version: 2
  tests:
    jobs:
      - test-9.4.0
      - test-9.3.1
      - test-9.3.0
