version: 2
references:
  test: &test
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      SPEC_OPTS: '--format documentation --format RspecJunitFormatter --out test_report.xml'
    steps:
      - checkout
      - restore_cache:
          key: 1-bundler-{{ checksum "xccoveralls.gemspec" }}
      - run: bundle install --path vendor/bundler
      - save_cache:
          key: 1-bundler-{{ checksum "xccoveralls.gemspec" }}
          paths:
            - vendor/bundler
      - run: bundle exec rake rubocop
      - run: bundle exec rake spec
      - run: bundle exec rake coveralls:push
      - run: bundle exec rake build
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: result.xml
      - store_artifacts:
          path: pkg

jobs:
  test-9.4.0:
    macos:
      xcode: '9.4.0'
    <<: *test

  test-9.3.1:
    macos:
      xcode: '9.3.1'
    <<: *test

  test-9.3.0:
    macos:
      xcode: '9.3.0'
    <<: *test

workflows:
  version: 2
  tests:
    jobs:
      - test-9.4.0
      - test-9.3.1
      - test-9.3.0
