version: 2
references:
  test: &test
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      SPEC_OPTS: '--format documentation --format RspecJunitFormatter --out test_output/result.xml'
    steps:
      - checkout
      - restore_cache:
          key: 1-bundler-{{ checksum "xccoveralls.gemspec" }}
      - run: bundle install --path vendor/bundler
      - save_cache:
          key: 1-bundler-{{ checksum "xccoveralls.gemspec" }}
          paths:
            - vendor/bundler
      - run: bundle exec rake rubocop
      - run: bundle exec rake spec
      - run: bundle exec rake coveralls:push
      - run: bundle exec rake build
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: pkg
          destination: pkg

jobs:
  test-9.4.0:
    macos:
      xcode: '9.4.0'
    <<: *test

  test-9.3.1:
    macos:
      xcode: '9.3.1'
    <<: *test

  test-9.3.0:
    macos:
      xcode: '9.3.0'
    <<: *test

  release:
    docker:
      - image: circleci/ruby:2
    steps:
      - checkout
      - run: gem build xccoveralls.gemspec
      - run: .circleci/check-tag.sh
      - run: .circleci/export-api-key.sh
      - run: gem push xccoveralls*.gem
      - store_artifacts:
          path: xccoveralls*.gem
          destination:

workflows:
  version: 2
  tests:
    jobs:
      - test-9.4.0
      - test-9.3.1
      - test-9.3.0
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
